version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
    container_name: crypto_apache
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
    networks:
      - crypto_network

  mysql:
    image: mysql:5.7
    container_name: crypto_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto
      MYSQL_USER: crypto
      MYSQL_PASSWORD: crypto
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/mysql-data:/var/lib/mysql
    networks:
      - crypto_network

networks:
  crypto_network:
    name: crypto_network
    driver: bridge